stages:
  - test
  - deploy

variables:
  HEROKU_APP_NAME: "ng13-hoodhelp-api"

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y heroku
    - heroku login -i
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
  only:
    - main
