services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-app"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - dbapp:/data/postgres-app
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    dbapp:
      external: true