name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      # Add other environment variables here as needed
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start Docker services
        run: docker-compose up -d
        
      - name: Display all secrets
        run: echo "${{ toJson(secrets) }}"

      - name: Display Environment Variables in Docker Container
        run: docker-compose run app env

      - name: Run tests
        run: docker-compose run app npm run test:ci

      - name: Stop Docker services
        run: docker-compose down
